<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter block_filter" >
        <button type="button" class="btn btn_filter">
            <span>
                <?= $block->escapeHtml(__('Filters')) ?>
                
                <div class="icon">
                    <i class="icon-plus fas fa-plus"></i>
                    <i class="icon-minus fas fa-minus"></i>
                </div>
            </span>
        </button>
        <div class="block-content filter-content">
            <div class="block-title filter-title">
                <strong><?= $block->escapeHtml(__('Shop By')) ?></strong>
            </div>
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if (!$wrapOptions) : ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
                    <dl class="filter-options" id="narrow-by-list">
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if ($filter->getItemsCount()) : ?>
                        <dt role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function(){
            $(".btn_filter").click(function(){
                $(".filter-content").toggleClass("active");
                $(".btn_filter").toggleClass("active");
                $(".sort_content").removeClass("active");
            });
        });
    });
</script>

